version: '3.5'

services: 
  nginx:
    image: nginx:1.17
    restart: always
    ports:
      - 80:80 
      #- 443:443
    volumes:
      - ./www/:/var/www/html     
      - ./data/certs/:/var/www/certs
      - ./data/conf.d/:/etc/nginx/conf.d
      - ./data/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - php
      - db  

  php:
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    volumes:
      - ./www/:/var/www/html
    depends_on:  
      - db 
  db:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    ports:
      - 3306:3306 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
    volumes:
      - ./data/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
